IF NOT EXISTS(SELECT * FROM SYS.OBJECTS 
	WHERE OBJECT_ID = OBJECT_ID(N'[Authors]') AND TYPE IN (N'U'))
BEGIN
	
	CREATE TABLE [Authors]
	(
		AuthorId INT IDENTITY(1,1),
		AuthorName VARCHAR(100) NOT NULL
	)

	ALTER TABLE [Authors]
	ADD CONSTRAINT PK_Authors PRIMARY KEY (AuthorId)

END