IF EXISTS(SELECT * FROM SYS.OBJECTS 
	WHERE OBJECT_ID = OBJECT_ID(N'[Books]') AND TYPE IN (N'U'))
BEGIN
	
	ALTER TABLE [Books]
	ADD BookTypeId INT NOT NULL

	ALTER TABLE [Books]
	ADD CONSTRAINT FK_Books_BookTypeId FOREIGN KEY (BookTypeId) REFERENCES BookType(BookTypeId)
END